//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/GamePlayAssets/Players Folder/controler input/leftSideInput 1.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @LeftSideInput1 : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @LeftSideInput1()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""leftSideInput 1"",
    ""maps"": [
        {
            ""name"": ""Normal"",
            ""id"": ""6a0d602c-839d-4fb0-8496-c03eb4b55820"",
            ""actions"": [
                {
                    ""name"": ""jump"",
                    ""type"": ""Value"",
                    ""id"": ""d25a83ab-0615-46d8-8deb-f7b8adfa4c8b"",
                    ""expectedControlType"": ""Dpad"",
                    ""processors"": """",
                    ""interactions"": ""Press(pressPoint=0.2)"",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""DashDown"",
                    ""type"": ""Button"",
                    ""id"": ""61a8d3e1-67d1-44b1-8946-c49a5a498a0f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""893859ec-2f2d-489c-bb83-ed7073a85b4c"",
                    ""path"": ""<Gamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d6bd001b-1109-4ba2-8c7b-48eec9c974d3"",
                    ""path"": ""<Gamepad>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DashDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""inverted"",
            ""id"": ""d1ffd256-b209-4690-8dc6-8c81a490e239"",
            ""actions"": [
                {
                    ""name"": ""JumpInverted"",
                    ""type"": ""Button"",
                    ""id"": ""7627e96d-b429-4fde-8a89-245cef16ebb6"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""DashDownInverted"",
                    ""type"": ""Button"",
                    ""id"": ""ffb7dde5-8da3-40ea-a9d9-f8d08352be64"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""3a71ec88-519c-4eb7-80d5-f84431d8771b"",
                    ""path"": ""<Gamepad>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""JumpInverted"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3d02c1df-73fe-4ad3-a147-2d334d11f6f9"",
                    ""path"": ""<Gamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DashDownInverted"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Normal
        m_Normal = asset.FindActionMap("Normal", throwIfNotFound: true);
        m_Normal_jump = m_Normal.FindAction("jump", throwIfNotFound: true);
        m_Normal_DashDown = m_Normal.FindAction("DashDown", throwIfNotFound: true);
        // inverted
        m_inverted = asset.FindActionMap("inverted", throwIfNotFound: true);
        m_inverted_JumpInverted = m_inverted.FindAction("JumpInverted", throwIfNotFound: true);
        m_inverted_DashDownInverted = m_inverted.FindAction("DashDownInverted", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Normal
    private readonly InputActionMap m_Normal;
    private INormalActions m_NormalActionsCallbackInterface;
    private readonly InputAction m_Normal_jump;
    private readonly InputAction m_Normal_DashDown;
    public struct NormalActions
    {
        private @LeftSideInput1 m_Wrapper;
        public NormalActions(@LeftSideInput1 wrapper) { m_Wrapper = wrapper; }
        public InputAction @jump => m_Wrapper.m_Normal_jump;
        public InputAction @DashDown => m_Wrapper.m_Normal_DashDown;
        public InputActionMap Get() { return m_Wrapper.m_Normal; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(NormalActions set) { return set.Get(); }
        public void SetCallbacks(INormalActions instance)
        {
            if (m_Wrapper.m_NormalActionsCallbackInterface != null)
            {
                @jump.started -= m_Wrapper.m_NormalActionsCallbackInterface.OnJump;
                @jump.performed -= m_Wrapper.m_NormalActionsCallbackInterface.OnJump;
                @jump.canceled -= m_Wrapper.m_NormalActionsCallbackInterface.OnJump;
                @DashDown.started -= m_Wrapper.m_NormalActionsCallbackInterface.OnDashDown;
                @DashDown.performed -= m_Wrapper.m_NormalActionsCallbackInterface.OnDashDown;
                @DashDown.canceled -= m_Wrapper.m_NormalActionsCallbackInterface.OnDashDown;
            }
            m_Wrapper.m_NormalActionsCallbackInterface = instance;
            if (instance != null)
            {
                @jump.started += instance.OnJump;
                @jump.performed += instance.OnJump;
                @jump.canceled += instance.OnJump;
                @DashDown.started += instance.OnDashDown;
                @DashDown.performed += instance.OnDashDown;
                @DashDown.canceled += instance.OnDashDown;
            }
        }
    }
    public NormalActions @Normal => new NormalActions(this);

    // inverted
    private readonly InputActionMap m_inverted;
    private IInvertedActions m_InvertedActionsCallbackInterface;
    private readonly InputAction m_inverted_JumpInverted;
    private readonly InputAction m_inverted_DashDownInverted;
    public struct InvertedActions
    {
        private @LeftSideInput1 m_Wrapper;
        public InvertedActions(@LeftSideInput1 wrapper) { m_Wrapper = wrapper; }
        public InputAction @JumpInverted => m_Wrapper.m_inverted_JumpInverted;
        public InputAction @DashDownInverted => m_Wrapper.m_inverted_DashDownInverted;
        public InputActionMap Get() { return m_Wrapper.m_inverted; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(InvertedActions set) { return set.Get(); }
        public void SetCallbacks(IInvertedActions instance)
        {
            if (m_Wrapper.m_InvertedActionsCallbackInterface != null)
            {
                @JumpInverted.started -= m_Wrapper.m_InvertedActionsCallbackInterface.OnJumpInverted;
                @JumpInverted.performed -= m_Wrapper.m_InvertedActionsCallbackInterface.OnJumpInverted;
                @JumpInverted.canceled -= m_Wrapper.m_InvertedActionsCallbackInterface.OnJumpInverted;
                @DashDownInverted.started -= m_Wrapper.m_InvertedActionsCallbackInterface.OnDashDownInverted;
                @DashDownInverted.performed -= m_Wrapper.m_InvertedActionsCallbackInterface.OnDashDownInverted;
                @DashDownInverted.canceled -= m_Wrapper.m_InvertedActionsCallbackInterface.OnDashDownInverted;
            }
            m_Wrapper.m_InvertedActionsCallbackInterface = instance;
            if (instance != null)
            {
                @JumpInverted.started += instance.OnJumpInverted;
                @JumpInverted.performed += instance.OnJumpInverted;
                @JumpInverted.canceled += instance.OnJumpInverted;
                @DashDownInverted.started += instance.OnDashDownInverted;
                @DashDownInverted.performed += instance.OnDashDownInverted;
                @DashDownInverted.canceled += instance.OnDashDownInverted;
            }
        }
    }
    public InvertedActions @inverted => new InvertedActions(this);
    public interface INormalActions
    {
        void OnJump(InputAction.CallbackContext context);
        void OnDashDown(InputAction.CallbackContext context);
    }
    public interface IInvertedActions
    {
        void OnJumpInverted(InputAction.CallbackContext context);
        void OnDashDownInverted(InputAction.CallbackContext context);
    }
}
