//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/ControlerInput/ControllerInputSystem.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @ControllerInputSystem : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @ControllerInputSystem()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""ControllerInputSystem"",
    ""maps"": [
        {
            ""name"": ""Player_1"",
            ""id"": ""1280705c-a876-4c7e-8744-4bffc72cd7fc"",
            ""actions"": [
                {
                    ""name"": ""Jump1"",
                    ""type"": ""Button"",
                    ""id"": ""ca8a6567-fc35-49a1-8f95-5554abd32625"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""DashDown1"",
                    ""type"": ""Button"",
                    ""id"": ""19a87445-b93a-4734-ab86-01b41c7b912d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""2b2a1809-adc3-4cab-88f8-dfab9888e01f"",
                    ""path"": ""<Gamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1d3ee93d-df66-4d41-8fb4-5c043b1298d5"",
                    ""path"": ""<Gamepad>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DashDown1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Player2"",
            ""id"": ""7f4fe0b3-9f66-4219-98d5-74cba8ca80b3"",
            ""actions"": [
                {
                    ""name"": ""Jump2"",
                    ""type"": ""Button"",
                    ""id"": ""cb494666-11e5-4658-ba28-e0745ce43f7f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""DashDown2"",
                    ""type"": ""Button"",
                    ""id"": ""a2bf692b-0fde-4f79-a8ff-7e177cc56fed"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""404efbda-2d58-4644-8fbc-6a1d06583827"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3f1fe034-6978-4920-9866-127cbfe2d063"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DashDown2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Player_1
        m_Player_1 = asset.FindActionMap("Player_1", throwIfNotFound: true);
        m_Player_1_Jump1 = m_Player_1.FindAction("Jump1", throwIfNotFound: true);
        m_Player_1_DashDown1 = m_Player_1.FindAction("DashDown1", throwIfNotFound: true);
        // Player2
        m_Player2 = asset.FindActionMap("Player2", throwIfNotFound: true);
        m_Player2_Jump2 = m_Player2.FindAction("Jump2", throwIfNotFound: true);
        m_Player2_DashDown2 = m_Player2.FindAction("DashDown2", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Player_1
    private readonly InputActionMap m_Player_1;
    private IPlayer_1Actions m_Player_1ActionsCallbackInterface;
    private readonly InputAction m_Player_1_Jump1;
    private readonly InputAction m_Player_1_DashDown1;
    public struct Player_1Actions
    {
        private @ControllerInputSystem m_Wrapper;
        public Player_1Actions(@ControllerInputSystem wrapper) { m_Wrapper = wrapper; }
        public InputAction @Jump1 => m_Wrapper.m_Player_1_Jump1;
        public InputAction @DashDown1 => m_Wrapper.m_Player_1_DashDown1;
        public InputActionMap Get() { return m_Wrapper.m_Player_1; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(Player_1Actions set) { return set.Get(); }
        public void SetCallbacks(IPlayer_1Actions instance)
        {
            if (m_Wrapper.m_Player_1ActionsCallbackInterface != null)
            {
                @Jump1.started -= m_Wrapper.m_Player_1ActionsCallbackInterface.OnJump1;
                @Jump1.performed -= m_Wrapper.m_Player_1ActionsCallbackInterface.OnJump1;
                @Jump1.canceled -= m_Wrapper.m_Player_1ActionsCallbackInterface.OnJump1;
                @DashDown1.started -= m_Wrapper.m_Player_1ActionsCallbackInterface.OnDashDown1;
                @DashDown1.performed -= m_Wrapper.m_Player_1ActionsCallbackInterface.OnDashDown1;
                @DashDown1.canceled -= m_Wrapper.m_Player_1ActionsCallbackInterface.OnDashDown1;
            }
            m_Wrapper.m_Player_1ActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Jump1.started += instance.OnJump1;
                @Jump1.performed += instance.OnJump1;
                @Jump1.canceled += instance.OnJump1;
                @DashDown1.started += instance.OnDashDown1;
                @DashDown1.performed += instance.OnDashDown1;
                @DashDown1.canceled += instance.OnDashDown1;
            }
        }
    }
    public Player_1Actions @Player_1 => new Player_1Actions(this);

    // Player2
    private readonly InputActionMap m_Player2;
    private IPlayer2Actions m_Player2ActionsCallbackInterface;
    private readonly InputAction m_Player2_Jump2;
    private readonly InputAction m_Player2_DashDown2;
    public struct Player2Actions
    {
        private @ControllerInputSystem m_Wrapper;
        public Player2Actions(@ControllerInputSystem wrapper) { m_Wrapper = wrapper; }
        public InputAction @Jump2 => m_Wrapper.m_Player2_Jump2;
        public InputAction @DashDown2 => m_Wrapper.m_Player2_DashDown2;
        public InputActionMap Get() { return m_Wrapper.m_Player2; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(Player2Actions set) { return set.Get(); }
        public void SetCallbacks(IPlayer2Actions instance)
        {
            if (m_Wrapper.m_Player2ActionsCallbackInterface != null)
            {
                @Jump2.started -= m_Wrapper.m_Player2ActionsCallbackInterface.OnJump2;
                @Jump2.performed -= m_Wrapper.m_Player2ActionsCallbackInterface.OnJump2;
                @Jump2.canceled -= m_Wrapper.m_Player2ActionsCallbackInterface.OnJump2;
                @DashDown2.started -= m_Wrapper.m_Player2ActionsCallbackInterface.OnDashDown2;
                @DashDown2.performed -= m_Wrapper.m_Player2ActionsCallbackInterface.OnDashDown2;
                @DashDown2.canceled -= m_Wrapper.m_Player2ActionsCallbackInterface.OnDashDown2;
            }
            m_Wrapper.m_Player2ActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Jump2.started += instance.OnJump2;
                @Jump2.performed += instance.OnJump2;
                @Jump2.canceled += instance.OnJump2;
                @DashDown2.started += instance.OnDashDown2;
                @DashDown2.performed += instance.OnDashDown2;
                @DashDown2.canceled += instance.OnDashDown2;
            }
        }
    }
    public Player2Actions @Player2 => new Player2Actions(this);
    public interface IPlayer_1Actions
    {
        void OnJump1(InputAction.CallbackContext context);
        void OnDashDown1(InputAction.CallbackContext context);
    }
    public interface IPlayer2Actions
    {
        void OnJump2(InputAction.CallbackContext context);
        void OnDashDown2(InputAction.CallbackContext context);
    }
}
